name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts
      - name: SSH into GCP VM and run commands
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} -i ~/.ssh/id_ed25519 \
          cd ~/llm-backend && \
      - name: docker build
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} -i ~/.ssh/id_ed25519 docker-compose build llm
      - name: docker up
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} -i ~/.ssh/id_ed25519 docker-compose down llm
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} -i ~/.ssh/id_ed25519 docker-compose up llm -d
